2020-01-02T13:00:27 - INITIAL_LOW - docs: Outline contribution guidelines
2020-01-05T12:26:20 - INITIAL_LOW - Initial setup: settings.yaml
2020-01-06T14:57:14 - INITIAL_LOW - docs: Outline contribution guidelines
2020-01-07T12:17:25 - INITIAL_LOW - Initial setup: settings.yaml
2020-01-09T09:50:12 - INITIAL_LOW - refactor: Initial project structure for config
2020-01-13T12:28:49 - INITIAL_LOW - refactor: Initial project structure for config
2020-01-27T09:26:34 - INITIAL_LOW - refactor: Initial project structure for config
2020-02-05T09:36:13 - INITIAL_LOW - refactor: Initial project structure for config
2020-02-05T10:13:16 - INITIAL_LOW - refactor: Initial project structure for config
2020-02-05T10:39:11 - INITIAL_LOW - chore: Add .gitignore
2020-02-16T15:23:28 - INITIAL_LOW - docs: Basic README for config
2021-05-11T12:16:39 - INITIAL_LOW - chore: Add .gitignore
2021-06-08T13:35:36 - INITIAL_LOW - chore: Add .gitignore
2021-06-08T13:52:12 - INITIAL_LOW - docs: Basic README for config
2021-06-09T11:31:39 - INITIAL_LOW - refactor: Initial project structure for config
